### PR TITLE
Add Safari build

### PR DESCRIPTION
**Pull request by fregante**
Follows https://github.com/sindresorhus/refined-github/pull/3677
Part of #112

### CODE REVIEW

**Comment by fregante** [comment]
## How to test

1. Install XCode 12 and Safari 14
2. You probably need to enable **Allow Unsigned Extensions** in Safari’s **Develop** menu.
3. Run:

	```sh
	npm run build
	npm run pack:safari
	npm run start:safari
	```

4. Click on the extension icon while on GitHub.com to enable it.

## Review

All the new files are autogenerated. Suggestions welcome, even if it's just to rename files.

## Next

I think this PR won't need substantial work, but it follows https://github.com/sindresorhus/refined-github/pull/3677#issuecomment-714249581

Required next steps:

- [ ] Signing
- [ ] Autodeploying

Since `npmhub` changes rarely, even just signing the extension once would be beneficial so we can link to it and people can install it freely.

**Comment by fregante** [comment]
Here's the built, but unsigned version, in the meanwhile: [npmhub.zip](https://github.com/npmhub/npmhub/files/5434008/npmhub.zip)

**Comment by sindresorhus** [comment]
Here's a signed build: [npmhub.app.zip](https://github.com/npmhub/npmhub/files/5434151/npmhub.app.zip)

I still had to enable "allow unsigned extensions" in Safari to make it show up though, which makes me suspect that only ones directly from the App Store will work by default.

**Comment by fregante** [comment]
Related to #115 

Safari-only icon:

**Pull request merged**
