### PR TITLE
Add support for Safari on iOS

### PR DESCRIPTION
**Pull request by fregante**
## Screenshot

Screen Shot 1

## Steps

To convert the extension, I completely replaced the old project:

1. `xcrun safari-web-extension-converter distribution/ --app-name 'npmhub' --bundle-identifier 'org.npmhub.npmhub`
3. `mv safari/.gitignore npmhub` (preserve file)
3. `trash safari` (delete old directory)
4. `mv npmhub safari` (rename)
5. Created a buncha new icons
6. Added the `LocalOverrides.xcconfig` file to the Xcode project, attaching it to both macOS and iOS apps
7. Deleted each "1.0" version override from the UI, this causes Xcode to read from the .xcconfig file
8. Added `persistent: false` to manifest.json
9. Dropped [com.apple.security.files.user-selected.read-only entitlement](https://github.com/npmhub/npmhub/pull/152/commits/f9e6fb15d86a0b80e1ebdcb0531a13a37e948f86) entitlement
10. etc

### CODE REVIEW

**Comment by fregante** [comment]
cc @sindresorhus do you know why this would fail here and not in RG? I regenerated the extension because my maintenance here can't be "copy-paste code I don't understand from RG" 😅

**Comment by sindresorhus** [comment]
No idea. I doubt it's related to the Xcode project though. I looked at the Xcode project, and nothing stood out to me.

If you enable the Develop menu in Safari, you can inspect the extension background page when running on iPhone or in the simulator.

**Comment by fregante** [comment]
Yeah that's actually where I'm seeing the error. When opening the background page I don't see anything, but if I reload I get that "contextMenu is undefined" error

In the content script I get an error in an inscrutable Svelte part that probably comes from the background page not responding… but who knows. It *should* work because it works elsewhere.

**Comment by fregante** [comment]
Yep, https://github.com/fregante/webext-domain-permission-toggle/pull/26 was the reason. Safari just closed the service worker on error and I wasn't able to see it.

It works now 😍 

Simulator Screenshot - iPhone 14 Pro - 2023-05-23 at 14 11 27

**Comment by fregante** [comment]
For the screenshots…

https://developer.apple.com/help/app-store-connect/reference/screenshot-specifications

**Pull request merged**
