### PR TITLE
Get extension version from git tag

### LINKED ISSUE #19: Autodeployment automation
Currently the deployment steps are:

0. Update the version in `extension/manifest.json`
0. Create a commit for it
0. Create a tag with the same version

If you're ok with it, I can skip the first two steps by dynamically update the version during deployment (without committing it)

You can see it in action on my GitHub Clean Feed:
- [.travis.yml](https://github.com/bfred-it/github-clean-feed/blob/648f8fe870e49053b4aeae1180285a1d6945853c/.travis.yml#L9)
- [package.json](https://github.com/bfred-it/github-clean-feed/blob/648f8fe870e49053b4aeae1180285a1d6945853c/package.json#L24-L26)
- [manifest.json](https://github.com/bfred-it/github-clean-feed/blob/648f8fe870e49053b4aeae1180285a1d6945853c/extension/manifest.json#L5)

### PR DESCRIPTION
**Pull request by bfred-it**
Closes #19

### CODE REVIEW

**Comment by zeke** [comment]
Didn't know about `dot-json`. Nice!

https://github.com/zeke/npe/commit/772d86a0fa80ad0bbcd531c5dea92e6e6cf7423c

**Comment by zeke** [comment]
So does this mean Travis will deploy master to the Chrome store automatically?

**Comment by bfred-it** [comment]
Until now, you had to manually change the manifest.json and then create a git tag, which would trigger a deploy on travis.

This PR changes it so you only need to create a git tag/release on GitHub.com

If you want it fully automatic we'd have to also pull the current version from the web store to bump it.

**Comment by bfred-it** [comment]
It looks complex https://github.com/ZenHubIO/chromepet/blob/master/src/chromepet.js

**Comment by zeke** [comment]
I use https://github.com/sindresorhus/np which does git tags automatically. Think that will do the trick?

**Comment by bfred-it** [comment]
Different approach. `np` is run locally and this PR enables us to deploy new changes directly from GitHub.com

`np` is npm-only anyway: https://github.com/sindresorhus/np/issues/92

**Comment by bfred-it** [comment]
One more thought: I can skip the tags entirely and just have Travis use the date as version number for every commit on master: `v2017.2.12` instead of `v2.1.1`

This would make it similar to `semantic-release` except that Chrome Extensions don't need semantic releases since Chrome only installs the latest. 

What do you say?

**Comment by zeke** [comment]
> What do you say?

👍

**Comment by bfred-it** [comment]
It looks like Travis got disconnected on the rename. I requested Github<->Travis org access to you.

**Pull request merged**
