### PR TITLE
Add link to jump directly to npmhub

### LINKED ISSUE #125: The dependency list is hard to reach
Reaching npmhub means _Scrolling all the way down, but not quite all the way._

I think it makes sense to somehow block the scroll once the user reaches the bottom, and _only then_ allow scrolling further.

This is generally achieved by only hiding the whole table once the bottom is reached. However maybe it should already generate it _before_ then, so that it will be ready.

### PR DESCRIPTION
**Pull request by shinenelson**
Re-opening #141 per https://github.com/npmhub/npmhub/pull/141#issuecomment-913015963

~This implements a partial resolution for #125. It is called partial because it is implemented only for the repository sidebar. It is yet to be implemented for the 2 other places that npmhub is activated :~
- ~`package.JSON` blob~
- ~sub-directory with `package.JSON`~

resolves #125

### Screenshots

**Repository Sidebar**
https://github.com/npmhub/npmhub

### CODE REVIEW

**Comment by shinenelson** [comment]
I left implementation on the other 2 areas because of lack of knowledge of integrating SVGs using javascript. Now that it is included via HTML ( svelte ), I think I can try integrating in the other 2 places too.

For the `package.json` blob, I had suggested putting it in the info header of the file :

**Comment by shinenelson** [comment]
## More Screenshots

### `package.json`
https://github.com/npmhub/npmhub/blob/main/package.json

image

### when `package.json` exists in a sub-directory
https://github.com/writefreely/writefreely/tree/develop/prose

image

---

My initial intention was to add the link to the right edge of the contributors row in the `package.json` blob since it had all of the empty space being _wasted_. But since the contributors row did not exist on a `tree`, I moved the link to the top `.hx_commit-tease` selector.

**Comment by fregante** [comment]
There's a problem with that exact position: there new button pushes the history link to the left https://isotropic.co/what-exactly-is-cumulative-layout-shift/

This made me realize we can probably just add a new npmhub icon next to the "Go to file" button on every page, including the home.

**Comment by fregante** [comment]
image

**Comment by fregante** [comment]
Thanks for the screenshots! I was able to review this without using my computer 😃

**Comment by shinenelson** [comment]
> image

Svelte **appends** components to the `target`. I recall seeing an error along the lines of `target.append is not a function` ( this was earlier during my testing with Svelte when I messed up passing the target as a string instead of a  DOM element ).

My point is that I am not sure whether it is possible to prepend elements with Svelte. A quick web search did not provide any straightforward answers.

Inspecting the DOM structure of the top `.file-navigation` bar, shows that all elements on that row are within a single `<div>` element which makes putting the link in between, harder.

The other option would be to replace the whole `<div>`; but I think that is overkill for this kind of injection only to avoid layout shift.

I will defer to @fregante's discretion and choice as to how to move forward.

**Comment by fregante** [comment]
You can create an element via `document.createElement`, prepend it as you normally would, and only then attach the svelte component.

The advantage over just creating the whole thing this way is that at some point we'll probably merge this component into the main one, via Portals.

Alternatively you can look into using portals yourself: https://github.com/romkor/svelte-portal

**Comment by fregante** [comment]
If you have time I'd love to have that button next to "Go to file"

**Pull request closed without merging**
