### PR TITLE
GitLab support

### PR DESCRIPTION
**Pull request by MatthieuLemoine**
As talked about in #32, this PR adds GitLab support.

For now it only supports gitlab.com but once #31 merged, it should also support private gitlab instances.

npmhub-gitlab

### CODE REVIEW

**Comment by bfred-it** [comment]
I don't think you need any conditionals. Just include the new classes in the existing selectors and HTML chunks. Likely GitHub already doesn't have GitLab's classes and viceversa. If they do, perhaps the selectors can be made more specific.

**Comment by zeke** [comment]
Wow. So cool to see this coming together!

**Comment by MatthieuLemoine** [comment]
@bfred-it You're right! I updated the PR accordingly. Still need a conditional for ``dependenciesHeader`` and ``devDependenciesHeader`` though.

**Comment by bfred-it** [comment]
Looking good! Thanks :)

It will be deployed soon

**Comment by bfred-it** [comment]
`v2017.2.12.825` is out :)

https://gitlab.com/Rich-Harris/buble/tree/master#dependencies

**Comment by zeke** [comment]
So cool!

https://twitter.com/zeke/status/831950994409914368

**Pull request merged**
